### ISSUE TITLE
URLs Are Modified BEFORE Redirector Processes Them

### ISSUE THREAD

**Issue by Anthony-Mal** [einaregilsson/Redirector#126] opened 2018-08-16 20:10 UTC
As a test, I wrote the following redirect.
.
.
Orignal URL
https://www.youtube.com/watch?v=Suw6F-Y8PIg&feature=youtu.be

Redirect Pattern
https://www.youtube.com/watch?v=*&feature=youtu.be
https://hooktube.com/watch?v=$1

Result
https://hooktube.com/watch?v=Suw6F-Y8PIg
.
.
Then, I entered the following URL into the address bar.
.
https://youtu.be/Suw6F-Y8PIg 
.
Obviously, this URL does not match the redirect pattern, but, nevertheless it works. Apparently, Youtube changes the above URL to 

https://www.youtube.com/watch?v=Suw6F-Y8PIg&feature=youtu.be

And, its the modified URL that actually gets processed by Redirector. I get the same result with Firefox  61 and Opera 55. Shouldn't Redirector change the link FIRST?

**Comment by einaregilsson** [comment] 2018-08-16 21:32
This is normal. If you look at the network requests for https://youtu.be/Suw6F-Y8PIg, completely without redirector, you'll see that Youtube itself does a 302 redirect to https://www.youtube.com/watch?v=Suw6F-Y8PIg&feature=youtu.be , and Redirector then processes that request. 

> Shouldn't Redirector change the link FIRST?

No, why? Redirector doesn't match the first url, so why would it change it?

**Comment by Anthony-Mal** [comment] 2018-08-17 01:38
If enter the following the URL into the address bar

(1) https://youtu.be/Suw6F-Y8PIg

Youtube will automatically change it to

(2) https://www.youtube.com/watch?v=Suw6F-Y8PIg&feature=youtu.be


Agreed. But what if I enter the following URL instead?

(3) https://hooktube.com/watch?v=Suw6F-Y8PIg

The above URL isn't addressed to Youtube, so Youtube shouldn't change it. And, that's why URL (1) shouldn't work with my redirect. Redirector should change URL 1 to URL 3, and only URL 3 should be entered. Perhaps I should have started from the beginning. I'll try to be as brief as possible. 

I'm using Firefox 62, and I wanted to stop videos from playing automatically whenever I load a page. So, in about:config I set <media.autoplay.enabled> to false. At first this remedy seemed to work, but eventually I realized that it causes playback problems on Youtube. I found out that whenever the video got stuck, I could get it to play by toggling to theater mode. So, I made a redirect that would give me a similar result.

Redirect 1
Input - https://www.youtube.com/watch?v=UOWiHR83q04
Output - https://www.youtube.com/embed/UOWiHR83q04

The embed URL usually works if I open the link in a new tab. However, there are a lot of videos that youtube won't allow you to embed, or play on another website. And, besides, my modified embed mode isn't really theater mode. You can play the video, but you can't browse, because you can't see the video previews. I needed a way to switch back to normal mode. So, I wrote another redirect to allow me to switch back to normal mode.

Redirect 2
Input - https://www.youtube.com/embed/UOWiHR83q04
Output - https://www.youtube.com/watch?v=UOWiHR83q04

My plan was to browse in normal mode, open video links in new tabs, and Redirect 1 would change the watch URL to an embed one. To get back to normal mode, I would simply refresh the page and Redirect 2 would change the embed URL back to the watch URL. Except, it turns out that each redirect will only work if the other redirect is disabled. 

It's as if the ouput of one redirect is being processed by the other one, essentially creating a loop that leads back to where you started from. To put it another way, if I am in normal mode, I can't get to embed mode unless I disable Redirect 2. If, on the other hand, I'm in embed mode, I can't get to normal mode unless I disable Redirect 1. 

I should point out that I only have this problem in Firefox. Both redirects work fine in Opera. As long as you open the link in a new tab, the embed URL will work. And, to go back to normal mode, all you have to do is refresh the page. But to get my redirects to work Firefox, I had to try something different. If you right-click on the video and Copy the URL, you'll get this link.

https://youtu.be/Suw6F-Y8PIg

As you so astutely pointed out, if you open the above link with both redirects disabled, Youtube will automatically change it to

https://www.youtube.com/watch?v=Suw6F-Y8PIg&feature=youtu.be

Now, if I disable Redirect 2, and use the feature link as an Exclude pattern in Redirect 1, I can use the youtu.be URL to get back to normal mode.


Orignal URL
https://www.youtube.com/watch?v=UOWiHR83q04

Redirect Pattern
https://www.youtube.com/watch?v=*
https://www.youtube.com/embed/$1

Exlude
https://www.youtube.com/watch?v=*&feature=youtu.be

Result
https://www.youtube.com/embed/UOWiHR83q04

**Comment by Anthony-Mal** [comment] 2018-08-17 20:06
So, the problem is, the output of Redirect 1 is also the input to Redirect 2, and the output of Redirect 2 is also the input to Redirect 1. If both redirects operate you get an infinite loop. I tried your suggestion (even before you suggested it actually), but it doesn't solve the problem. If you add extra code to the output of Redirect 2, you can use the superfluous code as an exclude pattern in Redirect 1. In other words, you can get Redirect 2 to work even if Redirect 1 is enabled. However, you can't get Redirect 1 to work with Redirect 2 enabled, because the output of Redirect 1 is NECESSARILY the input to Redirect 2.  So, you can't have an exclude pattern in Redirect 2. In the mean time, I found the answer, even though I don't know what the answer is. Perhaps you can enlighten me. 

It's really quite simple. Instead of using Youtube links, I switched to using Hooktube, and the problem vanished. The only difference from my original redirects is I changed www.youtube.com to hooktube.com. 


                                     Redirect 1

Input
https://hooktube.com/watch?v=t_ckYnsga3Y

Match & Redirect
https://hooktube.com/watch?v=*
https://hooktube.com/embed/$1

Output
https://hooktube.com/embed/t_ckYnsga3Y



                                       Redirect 2

Input
https://hooktube.com/embed/t_ckYnsga3Y

Redirect Pattern
https://hooktube.com/embed/*
https://hooktube.com/watch?v=$1

Output
https://hooktube.com/watch?v=t_ckYnsga3Y


So, what's the answer? Why does it work with Hooktube, but not with Youtube? For that matter, why does Youtube work in Opera, but not in Firefox?

**Comment by gkrishnaks** [comment] 2018-08-19 05:25
@Anthony-Mal Hi. I read this thread - sounds like Redirector addon works as intended and we are limited the webrequest API provided by chrome/firefox.  

Perhaps you can try enable Logging from popup to understand what happens in the code by checking logs in Browser Console. (not the F12 one.. Firefox Menu -> Web Developer -> Browser Console ..Or from Chrome Extensions view -> click background page -> console)

**Comment by einaregilsson** [comment] 2018-08-19 20:43
> Why does it work with Hooktube, but not with Youtube? For that matter, why does Youtube work in Opera, but not in Firefox?

Not sure. Might be different implementations of the redirection api, maybe one doesn't let the results of redirects get processed again.

Still don't really understand why you couldn't use the exclude pattern though, or two exclude patterns to cover both cases. But it can also be that Youtube in some cases doesn't do a normal page load, it might change dynamically and then use the history api to push a new url to the address bar, I don't know why it doesn't work.

**Comment by Anthony-Mal** [comment] 2018-08-20 22:07
"I read this thread - sounds like Redirector addon works as intended and we are limited the webrequest API provided by chrome/firefox."

It's not entirely a question of which browser I use. Even if I use Firefox, the addon works fine for most URLs, but for some odd reason it doesn't work properly with Youtube links. Yet, the defect  is partly dependent on the browser, since the Youtube redirect loop doesn't show up when I use Opera.


"Perhaps you can try enable Logging from popup to understand what happens in the code by checking logs in Browser Console. (not the F12 one.. Firefox Menu -> Web Developer -> Browser Console ..Or from Chrome Extensions view -> click background page -> console)"


1) I started with a new installation of Firefox. I find it convenient to use portable Firefox, because I can delete it and quickly install a new copy in a matter of minutes. 

2) I updated it to the latest version 61.0.2 

3) To avoid addon conflicts, I installed no other addons except for Redirector, which I updated to version 3.2.1.

I wrote the following two redirets. 

Redirect 1
https://www.youtube.com/watch?v=UOWiHR83q04
https://www.youtube.com/watch?v=*
https://www.youtube.com/embed/$1


Redirect 2
https://www.youtube.com/embed/UOWiHR83q04
https://www.youtube.com/embed/*
https://www.youtube.com/watch?v=$1

4) I tested the redirects. Redirect 1 works fine, so long as you open links in new tabs. The same result for Redirect 2. However, each redirect only works if the other one is disabled. You have to turn Redirect 2 off in order to use Redirect 1, and vice versa.

5) I enabled logging, on Redirector and then deleted all previous logs under Web Developper/Browser Console. 

6) I then opened youtube.com and immediately began to get error messages. I don't know what any of them mean, since I'm not a programmer. 


<source> element has no “src” attribute. Media resource load failed. www.youtube.com
All candidate resources failed to load. Media load paused. www.youtube.com
paper-tooltip: fade-in-animation not found! desktop_polymer.js:4474:67
paper-tooltip: fade-out-animation not found! desktop_polymer.js:4474:67
paper-tooltip: fade-in-animation not found! desktop_polymer.js:4474:67
paper-tooltip: fade-out-animation not found! desktop_polymer.js:4474:67
paper-tooltip: fade-in-animation not found! desktop_polymer.js:4474:67
paper-tooltip: fade-out-animation not found! desktop_polymer.js:4474:67

7) With both redirects enabled, I opened a youtube link in a new tab. As expected, the video failed to open in embed mode. That is, Redirect 1 doesn't work when Redirect 2 is enabled. 

8) I then checked the error logs. Here's what I got. 

LoginRecipes: getRecipes: falling back to a synchronous message for: moz-extension://d03c505c-e348-4f08-8219-4b929c494a90 LoginRecipes.jsm:243
[Show/hide message details.] this._recipeManager is null LoginManagerParent.jsm:84
LoginRecipes: getRecipes: falling back to a synchronous message for: moz-extension://d03c505c-e348-4f08-8219-4b929c494a90 LoginRecipes.jsm:243
[Show/hide message details.] this._recipeManager is null LoginManagerParent.jsm:84
LoginRecipes: getRecipes: falling back to a synchronous message for: moz-extension://d03c505c-e348-4f08-8219-4b929c494a90 LoginRecipes.jsm:243
[Show/hide message details.] this._recipeManager is null LoginManagerParent.jsm:84
LoginRecipes: getRecipes: falling back to a synchronous message for: moz-extension://d03c505c-e348-4f08-8219-4b929c494a90 LoginRecipes.jsm:243
[Show/hide message details.] this._recipeManager is null LoginManagerParent.jsm:84
LoginRecipes: getRecipes: falling back to a synchronous message for: moz-extension://d03c505c-e348-4f08-8219-4b929c494a90 LoginRecipes.jsm:243
[Show/hide message details.] this._recipeManager is null LoginManagerParent.jsm:84
LoginRecipes: getRecipes: falling back to a synchronous message for: moz-extension://d03c505c-e348-4f08-8219-4b929c494a90 LoginRecipes.jsm:243
[Show/hide message details.] this._recipeManager is null LoginManagerParent.jsm:84
<source> element has no “src” attribute. Media resource load failed. watch
All candidate resources failed to load. Media load paused. watch

**Comment by Anthony-Mal** [comment] 2018-08-20 22:46
"Still don't really understand why you couldn't use the exclude pattern though, or two exclude patterns to cover both cases." 

You can, if you manually change the URL in the address. I now have to different redirects. Redirect 1 only works if there is a backslash at the end of the address. Redirect 2 only works if there is NO backslash at the end of the address. Now, whenever I want to switch to embed mode, I type a backslash to end of the URL and then hit the return. Whenever I want to go back to normal mode, I remove the backslash and hit return. 

It's laborous, but at least it works. And, hooktube didn't solve my problem, since there are plenty of videos that you can't view unless your on youtube.com/

**Comment by einaregilsson** [comment] 2018-08-21 09:29
This seems to work fine for me in Firefox, both redirects work and don't chain together because of the exclude rule: (The extra errors in the console from youtube are there even without redirector)

![screen shot 2018-08-21 at 09 28 13](https://user-images.githubusercontent.com/557149/44393627-bfcba480-a524-11e8-9d5c-0fcd2b72c13d.png)

**Comment by Anthony-Mal** [comment] 2018-08-21 23:51
"The extra errors in the console from youtube are there even without redirector"

In other words, it doesn't look as if Redirector is causing the problem. And, even more importantly for me, if YOU see the errors TOO, that also rules out corruption of either my browser or my operating system. 
_
_

If I'm not mistaken, these are your two redirects:

	REDIRECT 1
Original URL
`https://www.youtube.com/embed/UOWiHR83q04`
Match
`https://www.youtube.com/embed/*`
Exclude
`*dontredirect*`
Redirect
`https://www.youtube.com/watch?v=$1&dontredirect`
Final URL
`https://www.youtube.com/watch?v=UOWiHR83q04&dontredirect`

	REDIRECT 2
Original URL
`https://www.youtube.com/watch?v=UOWiHR83q04`
Match
`https://www.youtube.com/watch?v=*`
Exclude
`*dontredirect*`
Redirect
`https://www.youtube.com/embed/$1?dontredirect`
Final URL
`https://www.youtube.com/embed/UOWiHR83q04?dontredirect`

_
"This seems to work fine for me in Firefox, both redirects work and don't chain together because of the exclude rule"

_
Ok, I'm browsing on Youtube and I see a video. If I move the mouse over the link and look in the lower left corner of the browser window, I'll see that the link is: 

`https://www.youtube.com/watch?v=UOWiHR83q04`

If I open this link in a new tab, Redirect 2 will change it to:

`https://www.youtube.com/embed/UOWiHR83q04?dontredirect`

Indeed, the video does play. Now, if I want to return to normal browsing mode, I refresh the page and... nothing happens. Why? Because Redirect 1 will automatically ignore any URL with the string 'dontredirect'.

Solution: Manually remove the 'dontredirect' string from the URL, and then hit the return. Repeat this step, if I want to go back to embed mode.

**Comment by einaregilsson** [comment] 2018-08-22 09:01
Ok, I see what you mean. That's just not a use case that is supported by Redirector. It could be solved if a redirect would be marked as "don't redirect the result of this" but I'm not sure that can be done well using the APIs available to us.

**Closed** 2019-12-12 15:41 UTC
