### ISSUE TITLE
[Info] Wayback Everywhere addon uses Redirector as its "engine"

### ISSUE THREAD

**Issue by gkrishnaks** [einaregilsson/Redirector#121] opened 2018-05-18 14:24 UTC
Hi,
Wished to share about my addon "Wayback Everywhere" which uses Redirector as its "engine".
Target audience - people who like archiving stuff to world's biggest digital library Internet Archive Wayback Machine - as they just browse and read (at no extra effort)  :1st_place_medal: 

https://github.com/gkrishnaks/WaybackEverywhere-Firefox 

It's an addon to **auto-redirect** every link opened from Twitter/other feeds to its archived version in Wayback Machine, and **auto-save** if not archived yet when you open the link.  Comes bundled with a default Excludes list (to provide a starting point to users) that won't redirect to Wayback Machine and addon tries to **auto-detect** and add domains to Excludes list as you browse + you can also add sites to Excludes list as you browse from Popup Menu.

Has some handy features like auto-toggle to Firefox "reader mode" for Archived Pages, open all links in a given page that matches a selector in the links, and also you can opt to have the addon disabled when browser starts and you can enable the addon from popup menu. 

Addon locally saves its "stats" - attaching mine after just 1 month of usage (released addon on April 15)
https://i.imgur.com/CNKqG12.png 
(*Redirected 2600 pages to archived version, newly auto-saved ~1500 pages* in 1 month) 

Your suggestions, feedback and issues are welcome.

Thanks again @einaregilsson for Redirector! :)  

Next version will have :  
1) As Wayback Machine makes all the links in an archived page to archived URLs, the addon will convert the links to "Live urls" if the hostname is in Excludes list. (for example, let's say some archived page has a Github link, and github is in Excludes list, upon click, it will remove the wayback part of URL and load live URL instead.  

2) Remove ?utm and other ?* things that sites add to URLs before redirecting to Wayback MAchine - so that clean links can get archived to wayback machine upon save. 

3) Update the "default excludes" with more hostnames.

**Comment by einaregilsson** [comment] 2018-05-18 23:43
Cool 👍

**Comment by einaregilsson** [comment] 2019-05-07 11:38
Closing, since this is not a bug or a feature request.

**Closed by einaregilsson** 2019-05-07 11:38 UTC
